version: '3.8'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: ProjectApp
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
      - ./php/:/usr/local/etc/php/
  nginx:
    image: nginx:1.19-alpine
    container_name: Project-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
      
  db:
    container_name: Project-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root 
    ports:
      - 3306:3306